### ISSUE TITLE
Feedback installers 

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#109]
Hi @paulhfu ,
this issue is for collecting feedback on the installers. 

For now I only have positive things to report:
- The CI runs through without an issue and the artifacts are uploaded to https://github.com/computational-cell-analytics/micro-sam/actions/runs/5707871215
- I tested the linux installer and it works.

@sushmita-nair and @Sagnik700: could you please test the windows installer?

@Marei33: could you please test the mac installer? 

For downloading the installers please follow the link above, and scroll to the bottom, then you can download the respective installer:

![image](https://github.com/computational-cell-analytics/micro-sam/assets/4263537/b4478637-9c86-424b-bd26-f6e73b2dc337)

**Comment by Marei33** [comment]
I downloaded the installer file, opened it and followed the steps (so just clicked on "Continue" or "Agree"). At the end, I selected at path on my computer. I tried it with the Home directory and a specific folder in my home directory, the installation failed with both paths. It started loading ("Configuring" and "Writing Files" ... till "Validating"), but then I got the error message I posted before.

**Comment by paulhfu** [comment]
Hi @Marei33, did you start the installer with admin privileges? If not, is the behavior the same if it is started from an admin user?

**Comment by paulhfu** [comment]
@constantinpape, maybe we have to sign and notarize the installer in the Macos build.

**Comment by Sagnik700** [comment]
@constantinpape @paulhfu I tried out the installation in Windows and everything got installed successfully. I am writing the steps for the 3 workflows that I followed and a few pointers that I noticed during the installation.
1. Downloaded installer and ran it as User(No admin rights). Default installation location was C:\Users\Sagnik. After that step, the option for `Add micro_sam to my PATH environment variable` was **selected by default** but it is written as Not Recommended, so maybe keeping it as deselected would be better. Installation got completed after that.
2. Uninstalled the application and then ran the installer from cmd with admin rights. Default selection during installation was All Users(Required admin privileges). Default installation path was C:\ProgramData which is a hidden folder in Windows 10, so maybe changing the default to Program Files would be better. Everything else looked perfect in this step.
3. Uninstalled the application and then again ran the installer from cmd with admin rights. Default selection during installation was All Users(Required admin privileges) but this time I selected `Just Me`. Default installation path was  C:\Users\Sagnik. After that step, the option for `Add micro_sam to my PATH environment variable` was **not selected by default** unlike workflow 1 which makes more sense. Everything else was fine.

Additional pointers: 
- Register micro-sam as my default Python 3.11 option was disabled is it was already selected in a previous installation and was not uninstalled, which I think is the expected behavior
- During the installation, can there be an option to cancel or abort? Because I cancelled the installation during its progress and wanted to see if it is removable or not if the installation encountered some external disruption in between like this. So I had to manually end the services that got installed(conda) during the time it was installing and then I could delete the installation folder.

**Comment by Marei33** [comment]
> 

I tried the installation again, now using the terminal with admin rights (opened it with the command "sudo -i" and navigated to the Download folder). I still get the same error message. 
<img width="697" alt="Screenshot 2023-08-01 at 15 27 15" src="https://github.com/computational-cell-analytics/micro-sam/assets/86373668/521d72ed-53b5-4027-826a-5984026b3a76">

**Comment by paulhfu** [comment]
Hi @constantinpape, I have not done this before. I did a quick search and it looks like that you need an apple account in order to get the certificates which are needed for signing.
I think in principle it is possible to do it on the command line (in the CI runner) we would have to inject the certificates and account ID as encrypted secrets.
In any case, developing this workflow directly in the runner will be not very efficient.

Resources:
https://help.apple.com/xcode/mac/current/#/dev60b6fbbc7
https://developer.apple.com/forums/thread/706758

**Comment by constantinpape** [comment]
Hi @paulhfu ,
thanks for the links!

> In any case, developing this workflow directly in the runner will be not very efficient.

I agree, that would not be a good set-up to develop this.

I will go ahead and ask some people from the ilastik team if they have to do this for ilastik and if they think this is really the issue, before we start fixing something that's not really the problem...

**Comment by constantinpape** [comment]
The feedback from @k-dominik was to look into what `napari` is doing. Indeed, they are building their tools with conda constructor and have a quite good documentation: https://napari.org/0.4.17/developers/packaging.html#constructor-based-installers
Can you have a look at this @paulhfu and see if it might help with the Mac issues? (And maybe also improves some other things?)

**Comment by paulhfu** [comment]
Hi @constantinpape, apart from what we are doing in the constructor script they are setting the default installation path and they are signing the installer. (See [here](https://github.com/napari/packaging/blob/f860505a0f605cd28908e945de8557bf87d81c74/.github/workflows/make_bundle_conda.yml#L338) and [here](https://github.com/napari/packaging/blob/f860505a0f605cd28908e945de8557bf87d81c74/.github/workflows/make_bundle_conda.yml#L448))
I think for the latter we can use their ci workflow as starting code. What we need are a developer certificate and identity.

Also they are testing their installers within the workflow. I would like to do that as well.

**Comment by constantinpape** [comment]
We figured out now that signing costs 100$ per year, and also that without signing it will be more difficult to install on Mac because users would need to disable some security features. (This is maybe why it doesn't work for @Marei33).
My preferred solutions now would be to:
- Use the bundled app solution (what ilastik is doing). @k-domink could you provide a link to show what you're doing there? Thanks!
- If that's too much effort to maintain besides the conda constructor, then either provide the installer as is, or don't provide a MAC installer.

**Comment by k-dominik** [comment]
Heya, our release process is outlined here: https://github.com/ilastik/ilastik-conda-recipes/tree/c8a00498e19f9d63653c91617e0dec7cdfe45b59/packaging/osx (we moved it to gitlab since for better maintainability with the actual release building). Central to it is the `[create-osx-app.sh](https://github.com/ilastik/ilastik-conda-recipes/blob/c8a00498e19f9d63653c91617e0dec7cdfe45b59/packaging/osx/create-osx-app.sh)` script, that does the env creation, py2app invocation, moving of the env and compression of the package.

**Comment by Marei33** [comment]
Hi @constantinpape, @paulhfu, @k-dominik,

I tried the installation again using the Mac installer, but I still have the same issues. 
I think the signing process is not the reason of the problem. When I download the .zip file from ownCloud, I can't open it directly because I get the warning that this software is from an unidentified developer. But then I have the option to click "Open anyway" under "Settings/Privacy and Security" and then the GUI installer can be opened. 

I tried the installation by two ways:

1. GUI Installer: 
Here I simply clicked " Continue", agreed to the software license agreement and selected that the package should be installed in the home directory. Then the installer starts the process, but after a few seconds I get the same error message as before: „The installation failed. The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.“

2. Via Terminal with admin rights: 
I opened the terminal with admin rights via the command „sudo -i“, changed to the folder ‚Downloads‘ and ran the installer via „installer -pkg micro_sam-0.2.1posti-MacOSX-×86_64.pkg -target /Users/marei/micro_sam_installation“. There, I got the same error message. You can see the exact output on the screenshot.

<img width="624" alt="Screenshot 2023-08-20 at 15 19 53" src="https://github.com/computational-cell-analytics/micro-sam/assets/86373668/5dd9d6a8-bccd-492f-81fd-45b8f560929f">
<img width="638" alt="Screenshot 2023-08-20 at 15 25 52" src="https://github.com/computational-cell-analytics/micro-sam/assets/86373668/823eab93-bf14-4ba1-a495-4391cfe42823">

**Comment by constantinpape** [comment]
Thanks for the detailed report @Marei33! For now I will remove the mention of the Mac installer from the documentation, and I will think about how we can better test this. (@paulhfu doesn't have access to a Mac, so debugging this is pretty inconvenient for him.)

**Comment by paulhfu** [comment]
Hi @Marei33, thank you for the testing effort!
I hope that I am able to provide a (non installer based) bundled version of the MacOs application by tomorrow.

**Comment by constantinpape** [comment]
We need to revisit the installers after having the napari plugin.
