### ISSUE TITLE
`AttributeError` in `amg.initialize` when using tiled pre-comuted embedding.

### ISSUE THREAD

**Issue by JoOkuma** [computational-cell-analytics/micro-sam#154]
Hey @constantinpape,

micro-sam is excellent. I really enjoy using it.

I'm trying to process larger 2D images and I'm getting an error when executing `amg.initialize` with `image_embeddings` parameter.
You can reproduce it with this:

```python3
import napari
from tifffile import imread
from micro_sam import instance_segmentation, util


if __name__ == "__main__":
    image = imread("Fluo-N2DL-HeLa/01/t000.tif")

    predictor = util.get_sam_model(device="cuda:0")
    amg = instance_segmentation.AutomaticMaskGenerator(predictor)   

    embeddings = util.precompute_image_embeddings(
        predictor, image,
        # after commeting the line below works
        save_path="/tmp/micro-sam/embeddings.zarr", tile_shape=(1024, 1024), halo=(128, 128)
    )
    amg.initialize(image, embeddings, verbose=True)

    instances_amg = amg.generate(pred_iou_thresh=0.88)
    instances_amg = instance_segmentation.mask_data_to_segmentation(
        instances_amg, shape=image.shape, with_background=True
    )

    v = napari.Viewer()
    v.add_image(image, colormap="magma")
    v.add_labels(instances_amg)

    napari.run()
```

Error:

```python3
Traceback (most recent call last):
  File "/home/jordao/miniconda3/envs/sam/lib/python3.10/site-packages/zarr/hierarchy.py", line 520, in __getattr__
    return self.__getitem__(item)
  File "/home/jordao/miniconda3/envs/sam/lib/python3.10/site-packages/zarr/hierarchy.py", line 500, in __getitem__
    raise KeyError(item)
KeyError: 'ndim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jordao/sam_bug.py", line 18, in <module>
    amg.initialize(image, embeddings, verbose=True)
  File "/home/jordao/miniconda3/envs/sam/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jordao/miniconda3/envs/sam/lib/python3.10/site-packages/micro_sam/instance_segmentation.py", line 442, in initialize
    util.set_precomputed(self._predictor, image_embeddings, i=i)
  File "/home/jordao/miniconda3/envs/sam/lib/python3.10/site-packages/micro_sam/util.py", line 554, in set_precomputed
    assert features.ndim in (4, 5)
  File "/home/jordao/miniconda3/envs/sam/lib/python3.10/site-packages/zarr/hierarchy.py", line 522, in __getattr__
    raise AttributeError
```
Commenting the indicated line avoids the issue.

The sample data can be downloaded from [here](http://data.celltrackingchallenge.net/training-datasets/Fluo-N2DL-HeLa.zip)

**Comment by constantinpape** [comment]
Hi @JoOkuma ,
thanks for the error report, I will have a look later.

> micro-sam is excellent. I really enjoy using it.

Thanks for the feedback!

Since you have some relevant expertise ;) : if you have some more detailed feedback (or would like to contribute at some point) that would be highly welcome.

I will send out a small "micro-sam newsletter" in the next few days, I will just go ahead and include you.

**Comment by constantinpape** [comment]
Ok, I double checked. This is actually expected behavior: 
if you use tiled embeddings you need the class [TiledAutomaticMaskGenerator](https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/instance_segmentation.py#L769) instead of `AutomaticMaskGenerator`.
If you replace it all works. (Both classes have the same interface)

Note: I just added a convenience function [get_amg](https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/instance_segmentation.py#L1094) that builds the correct AMG class. (You have to pass the boolean `is_tiled` to indicate whether you use tiling or not.)

**Comment by JoOkuma** [comment]
Thank you!
