### ISSUE TITLE
Remove clashes with napari built-in keybindings

### ISSUE THREAD

**Issue by GenevieveBuckley** [computational-cell-analytics/micro-sam#195]
I've noticed that some of the keybindings in micro-sam overlap with the built-in keybindings in napari. This makes micro-sam inconvenient to use. We should re-work the keybindings to avoid clashes wherever possible.

There is a list of (most? all?) napari keybindings in the preferences menu: `napari` > `Preferences` > `Shortcuts`
You should also be able to open the keybindings preference menu using the shortcut: `Control` + `C` (or `Command` + `C`)

The specific example I found was that the `V` keybinding, which usually toggles visibility of the selected layer(s) in napari, is overwritten by micro-sam to segment volumes with the 3D annotator. I often want to toggle the label layer off and on so I can see how well I think the segmentation matches the original image data, and not being able to use the `V` shortcut for this makes things much more inefficient.

**Comment by constantinpape** [comment]
Thanks for bringing this up, that's a very good point. We should fix this while working on #167.

I will have a closer look at the details tomorrow.

**Comment by constantinpape** [comment]
I checked the keybindings, and I think `V` is the only one that clashes with an existing one.
We should def. change that (and given the updated plans we discuss can do that before #167).

We have two options:
- We don't provide a key binding, since volume segmentation / tracking takes longer anyways, so having a key binding doesn't change that much time.
- Switch to some other key binding. I would suggest `Ctrl + V` or `Shift + V`.

What do you think @GenevieveBuckley?

**Comment by GenevieveBuckley** [comment]
True, I guess we could just not have a keybinding for it. Still, it might be nicer if we could think of a good keybinding.

I don't think we should use `Ctrl + V`, since that's already associated closely with copy-paste commands.
Maybe `Shift + V`, or `Shift + S` (since we already have `S` for segmenting one slice, this might be a good extension to segmenting all the slices). I'll have a think.

**Comment by constantinpape** [comment]
This is now resolved!
