### ISSUE TITLE
Documentation: add description of parameters and functionality

### ISSUE THREAD

**Issue by GenevieveBuckley** [computational-cell-analytics/micro-sam#197]
Constantin gave a good user tip in [this comment](https://github.com/computational-cell-analytics/micro-sam/pull/196#issuecomment-1727192702). I think it's a good tip, and it would be nice to include/highlight this in the micro-sam documentation.

https://github.com/computational-cell-analytics/micro-sam/pull/196#issuecomment-1727192702
>> I've found it helps to get your line close to the edge of the object you want to segment. Too far inside or outside give you poorer results (understandable, and I didn't find it too annoying - there is a little bit of flexibility & you don't have to be too precise)
>
> In these cases it might help to increase the box_extension parameter.

**Comment by constantinpape** [comment]
In general: parameters and functionality need to be documented better.
This is def. on my agenda, but I am a bit hesitant to invest much time now, since the user interface will change a bit with all the changes for the plugin. I have renamed the issue to broaden the scope a bit.
For now, let's collect relevant links here. I will start with two forum threads with user questions about parameters and finetuning:
- https://forum.image.sc/t/tracking-fast-moving-cells/86389
- https://forum.image.sc/t/finetune-micro-sam-on-your-own-data/86544

**Comment by constantinpape** [comment]
I am closing this in favor of #501. Note that we also have tooltips for the UI now which we can use for documenting the parameters.

**Comment by anwai98** [comment]
- > at: CP - Also relevant: https://github.com/computational-cell-analytics/micro-sam/issues/197 on parameter documentation, which has some relevant links.
