### ISSUE TITLE
precompute_state failed to run due to ndim

### ISSUE THREAD

**Issue by Conecsion** [computational-cell-analytics/micro-sam#208]
"ValueError: Invalid dimesionality 2, expect 2 or 3 dim data" when I run "micro_sam.precompute_state -n 2" in zsh command line

It seems that argparse took "--ndim 2" as a string type instead of int

**Comment by constantinpape** [comment]
Thanks for raising this, @Conecsion!
Indeed, the `int` specification was missing for that argument.

It should be fixed now. To use the fix:
- Pull the latest master branch.
- Install `micro_sam` again via `pip install -e .` (we switched some logic in the installation script, that's why you need to run the installation again)
