### ISSUE TITLE
annotate a serie of images using your script does not work for rgb.

### ISSUE THREAD

**Issue by koopa31** [computational-cell-analytics/micro-sam#38]
Hi,
After the discussion we had on image sc forum, I tried the image_series_annotator and I have a few questions. 
I made a folder composed of several RGB images. The first problem that I have is that they do not have all the same size which seems pretty natural. Hence np.stack cannot work. Moreover, when building the stack if images are RGB, the stack is 4D and the embeddings cannot be computed. I think I understand that for efficiency reasons, you try to compute the embeddings on the whole stack at the beginning, the problem is that it does not work in this type of case. Hence, in my case, wouldn't it be better to compute the embedding image per image, each time I load the next one, without using the stack ?
Thanks !

**Comment by koopa31** [comment]
Another question: why is embeddings pre computation taking 1,5h ?

**Comment by constantinpape** [comment]
Hi @koopa31 and sorry for the slow response (had a pretty busy week),
 
> I made a folder composed of several RGB images. The first problem that I have is that they do not have all the same size which seems pretty natural. Hence np.stack cannot work. Moreover, when building the stack if images are RGB, the stack is 4D and the embeddings cannot be computed. I think I understand that for efficiency reasons, you try to compute the embeddings on the whole stack at the beginning, the problem is that it does not work in this type of case.

Yes, that summarizes it correctly. For the example case I assume the same image size, and precompute the embeddings for efficiency reasons. Indeed this does not work (at least not as in the example) if the images have different sizes.
In this case you have two options:

## Don't precompute images

 This has the downside that it takes quite long to load the next image, especially if you are using a CPU, where computing the embeddings takes ~ 1 min, depending on the image size (if you are using it with a GPU it's usually just a few seconds). For this option you would just need to change [these lines](https://github.com/computational-cell-analytics/micro-sam/blob/master/examples/image_series_annotator_app.py#L33-L35) to remove the embedding precomputation and to put the images in a list instead of stacking them. Then you would need to update `_next` [here](https://github.com/computational-cell-analytics/micro-sam/blob/master/examples/image_series_annotator_app.py#L87) to compute the embeddings instead of loading the pre-computed ones. 
It should enough to replace `util.set_precomputed` with `util.precompute_image_embeddings(PREDICTOR, images[next_image_id])` for this.
 
## Change the precomputation logic

Instead of using the current precomputation [here](https://github.com/computational-cell-analytics/micro-sam/blob/master/examples/image_series_annotator_app.py#L34-L35) you would need to loop over the images and pre-compute the embeddings for each individual image rather than for the stacked images. (This will do more or less the same).
You would just need to replace the code with this loop (not tested!):
```python
images = [imageio.imread(p) for p in image_paths]
image_embeddings = []
for im_id, image in enumerate(images):
    embedding_save_path = f".../image_embeddings_{im_id}.zarr"
    this_embeddings = util.precompute_image_embeddings(PREDICTOR, image, save_path=embedding_save_path)
util.set_precomputed(PREDICTOR, image_embeddings[0])
```
and then you do `util.set_precomputed(PREDICTOR, image_embeddings[next_image_id])` [here](https://github.com/computational-cell-analytics/micro-sam/blob/master/examples/image_series_annotator_app.py#L87).

**Comment by koopa31** [comment]
Thank you for your answer. I got several questions:
1) According to me, in all cases, after precomputing embeddings, if I don't do: `util.set_precomputed(PREDICTOR, image_embeddings)`
it ain't gonna be taken into account.
2) It seems like you can't process an RGB image as it is considered as a 3-channel 3D image. Then, you must choose to load embeddings from one of the three RGB channels, hence you lose info. So maybe it's better to turn the image into a grayscale one before?
3) When I click n to load next image, I try to compute the embeddings of the new image to replace the old ones, and I get a memory problem. It seems that the memory isn't released automatically:
`    def _next(v):
        nonlocal next_image_id
        global image_path
        if next_image_id == 0:
            next_image_id += 1
        v.layers["image"].data = imread(image_paths[next_image_id])
        PREDICTOR = util.get_sam_model()
        image_embeddings = util.precompute_image_embeddings(PREDICTOR, np.transpose(v.layers["image"].data, (2, 0, 1)))
        util.set_precomputed(PREDICTOR, image_embeddings, i=0)

        v.layers["segmented_object"].data = np.zeros(v.layers["image"].data.shape[:2], dtype="uint32")
        v.layers["prompts"].data = []`
You can see I'm also reloading the NN, which I am not sure is necessary. But in all cases I got this issue with memory.

**Comment by constantinpape** [comment]
> 1. According to me, in all cases, after precomputing embeddings, if I don't do: `util.set_precomputed(PREDICTOR, image_embeddings)` it ain't gonna be taken into account.

Yes, that's correct. (I am not sure if I said anything to the contrary before, but if I did please disregard that ;))

> 2\. It seems like you can't process an RGB image as it is considered as a 3-channel 3D image. Then, you must choose to load embeddings from one of the three RGB channels, hence you lose info. So maybe it's better to turn the image into a grayscale one before?

You can process RGB, but you need to pass the channel axis last (i.e. the input image needs the shape (Y, X, 3)).
For reference here's the function that handles the incoming data: https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/util.py#L108 (and as you can see it can deal with both grayscale and RGB).

> 3\. When I click n to load next image, I try to compute the embeddings of the new image to replace the old ones, and I get a memory problem. It seems that the memory isn't released automatically:

All memory should be released, and you also don't need to reload the model, it wouldn't help with this (but will cost time!)
Hmm, maybe the image is just too large? You could try running with `vit_b` first, which would need less memory:
```
PREDICTOR = util.get_sam_model(model_type="vit_b")
```

**Comment by koopa31** [comment]
Thank you. I think I solved the memory problem. Nevertheless, processing RGB image  does not work. For instance, I tried to process an image of shape 3644, 2212, 3, and I get this error:
![image](https://github.com/computational-cell-analytics/micro-sam/assets/45684783/e0c788c7-56b8-48d2-9dab-7fa28bf392ca)
which shows it tries to compute along the first axis. That's why at first I tried to reshape my RGB image like (3, M, N) so it's processed as a 3D image but it's not satisfying. Maybe there's something I misunderstood. In the script called to_image, an M,N,3 image is directly provided to the NN, so that should work. 

One more question. I noticed that segmenting long objects in biology does not work. I supposed it's linked to the architecture and the embeddings size, or maybe not ^^I saw you started to implement a tiling function. Is that a solution to that problem to process the images by blocks of reasonable size?
Thank you :)

**Comment by koopa31** [comment]
I made a pull request to propose some improvements to the code so it is more versatile and enables the user to manually smooth the result if he can't reach something satisfying enough. I guess it could help some people as I am convinced I am not the only one who would like to process of series of images. Maybe this image series feature should be more highlighted, I don't know. In all cases, thanks for developing that.

**Comment by constantinpape** [comment]
Thanks, I will have a look at the PR later. (I am still not quite sure why it doesn't work for RGB, but I will comment on this in the PR).

> Maybe this image series feature should be more highlighted, I don't know. In all cases, thanks for developing that.

I will think about it. (I agree in principle, but also don't want to add to many things to maintain right now).

**Comment by koopa31** [comment]
Yes I understand perfectly. Regarding the processing by tiles, is it a feature to process images by blocks when they are too big to get good result?

**Comment by constantinpape** [comment]
> Regarding the processing by tiles, is it a feature to process images by blocks when they are too big to get good result?

Yes, exactly. Segment Anything works best for images of size 1024 x 1024, and when they get much larger doesn't work well. Tiling helps by running only for subparts of the image of a suitable shape. (I am working on choosing the tiling automatically when the image gets too large.)

> Would you mind if I share my adaptation to image series processing on imagesc forum for those who would be interested ?

No, I don't mind at all, please go ahead and share it. (And feel free to tag me there as well.)

**Comment by constantinpape** [comment]
I will go ahead and close this since our discussion moved on. See my comments in #52 and the implementation for the "proper" image series annotator in #56.
