### ISSUE TITLE
Update the Documentation for Mac Installation

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#41]
- Update python version (=3.10)
- Check for working PyTorch version on Mac (and update it likewise)
- Use `mamba` for installations (much faster)

**Comment by anwai98** [comment]
Quick try-outs:
- `pip` tricks didn't work because `numpy` from pip gets overwritten by any major conda/mamba installs, and `torch` doesn't seem to like it (troubles increase because of this issue)

**Comment by anwai98** [comment]
Follow-up:
- The Mac documentation works for M1 Chip (update: python needs to be depreciated to something like python 3.10)
- M2 Chip has conflicts with `mkl`, need to checkout issues at PyTorch.

**Comment by constantinpape** [comment]
I talked with @k-dominik about this and we concluded that it's highly unlikely that this issue depends on whether the user has a M1 or M2 (because this cannot affect which conda package is installed, and if the correct `osx-arm64` conda package is installed it does not install a pytorch version compiled with `mkl`.)
More likely this has just been a coincidence that has been due to outdated conda for the M2 users we have tried this with.
To really double check we would need to test this on an M2 with a fresh conda installation (ideally mambaforge or minimamba...)

**Comment by Jujhar** [comment]
typo, ignore above mention (meant issue 71 not 41)
