### ISSUE TITLE
Artifactual Segmentation "Rings" after Automatic Segmentation (2D)

### ISSUE THREAD

**Issue by ian-coccimiglio** [computational-cell-analytics/micro-sam#416]
Hi there,

Loving the tool, thank you for producing it. I've been using it today, but I noticed that often, a label image will include a 1-pixel wide ring that surrounds the mask with a unique label ID.

These occur on images including the sample blobs image from FIJI (using the Vit_B model)
<img src="https://github.com/computational-cell-analytics/micro-sam/assets/62724583/46c3cf39-f623-4265-a6c7-f08b4162d469" width="500" height="300">

As well as on the HELA example (using the Vit-H model)
<img src="https://github.com/computational-cell-analytics/micro-sam/assets/62724583/15a14381-acb6-487f-9ccf-c84d2633b6b9" width="500" height ="300">

The same appears on the tutorial [video](https://www.youtube.com/watch?v=ket7bDUP9tI):
<img src="https://github.com/computational-cell-analytics/micro-sam/assets/62724583/bd20f071-b81a-4384-a943-72e257237aff" width="500" height ="300">

These labels can pose problems for downstream analysis and exports. They aren't subsetted by the "minimum object size", possibly because their total polygonal area exceeds it.

A possible reason this might be happening could be in the translation between the SAM mask representation to the Napari label representation. If the SAM model detects two masks that super-impose on top of one another, it could be that micro-SAM is flattening them onto a 2D representation which captures the outline of the larger mask, and the area of the smaller mask. I noticed that this could happen when I was working with it using ultralytics on [image.sc](https://forum.image.sc/t/creating-label-images-with-the-segment-anything-model-guide/93224/2).

Or maybe it's something else, but it's worth looking into.

**Comment by constantinpape** [comment]
Hi @ian-coccimiglio,
thanks for bringing this up!

The reason for this problem is the following:
- The object masks are computed "independently" and then merged together to obtain the single channel label masks.
- In this process, it can happen that two almost identical objects get overlaid, leading to the ring effects.

We should absolutely work on mitigating this, and there are two approaches for this:
- Increase the `nms_threshold` parameter. This controls the degree to which intersecting objects are suppressed. We are currently not exposing this parameter in the GUI, but it's easy to add this.
- Also apply the `min_object_size` after intersection. Currently, we only apply it before the intersection, hence these artifacts are not filtered out.

We are currently working on a new release that will update the UI and introduce new functionality. I will include these extensions in there and ping you here once it's ready to be tested.

**Comment by constantinpape** [comment]
@ian-coccimiglio this issue is fixed on the `dev` branch now, we will merge this into `master` and make a new release soon.
It's ready to be tested on `dev` already, but note that the UI there has changed a bit and that these changes are not yet documented.

**Comment by constantinpape** [comment]
This is now implemented and the release is out. We have not fully updated the documentation for the new release but will update all the documentation in a few days and then also announce the release more widely.

I will go ahead and close this @ian-coccimiglio. Let us know if you have time to test it and if something does not work as expected.
