### ISSUE TITLE
problem with installing on windows (elf.io)

### ISSUE THREAD

**Issue by AlexandraLoewe** [computational-cell-analytics/micro-sam#440]
Hello there,

I try to install and run the micro_sam.annotator on windows.
Created an enviroment, cloned the micro-sam repo, installed it and all of the listed requirements and still run into "modules not found"-errors (vigra, elf) . I installed step by step every module which was missing and now I installed the module "elf" which brings me the error: "ModuleNotFoundError: No module named 'elf.io'"

Please, can you update the requirements.txt and also let me know how to handle that problem? 🙏

**Comment by anwai98** [comment]
Hi @AlexandraLoewe,

Thanks for your interest in `micro-sam`.

Looks like `elf` and/or `vigra` couldn't be installed. Apologies for the inconvenience. Let's check out the issue.

```
$ mamba list | grep -e "vigra" -e "elf"
```

If it misses either `elf`/`python-elf` or `vigra`, then `elf` and/or `vigra` didn't install. You can install them with the following command:
```
$ mamba install -c conda-forge python-elf vigra
```
For sanity check for the mentioned issue with `elf`, you can try:
```
$ python -c "import elf; from elf import io; print(elf.__version__); print(io)"
```
The outputs should look like:
```
0.5.0
<module 'elf.io' from 'here/is/your/elf/io/__init__.py'>
```

Let us know if this worked.

For our feedback, can you also confirm if you used the installation from [source](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-source) or one of the yaml script for installation? (ideally, it would be nice if you could post the steps for installation, so that we can reproduce the issue and take care of it)

**Comment by constantinpape** [comment]
Hi @AlexandraLoewe ,

just one more clarification:

> Please, can you update the requirements.txt

Our package has to be installed via conda / mamba and **cannot** be installed via pip. So we do not have a `requirements.txt`. (You may have used [requirements-dev.txt](https://github.com/computational-cell-analytics/micro-sam/blob/master/requirements-dev.txt), but this is only for installing additional developer tools).

For installation on windows please use `mamba` following the instructions [here](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-mamba).

**Comment by AlexandraLoewe** [comment]
@constantinpape  alright! Thank you for the Information. I tried the instructions you sent and got the failure from #407 with the never ending solving of the enviroment. 
I also tried the workaround listed in that Issue, installed elf by hand and now I have the next problem: "ModuleNotFoundError: No module named 'nifty.tools'". I already installed nifty but that seems to be the wrong package (or was updated and now has no tools anymore?). But I can't find another one.

**Comment by constantinpape** [comment]
This is the correct nifty repository @AlexandraLoewe https://github.com/conda-forge/nifty-feedstock
I would advise you to start with a new environment though. Once you have wrong dependencies installed it can be very difficult to update dependencies. (This is an unfortunate issue with python packaging...)

**Comment by AlexandraLoewe** [comment]
@constantinpape now it opens the annotator. Thank you!
