### ISSUE TITLE
Put on napari hub

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#530]
https://www.napari-hub.org/

**Comment by GenevieveBuckley** [comment]
Discussed previously here: https://forum.image.sc/t/publish-napari-plugin-with-conda-dependencies/65653

Summarizing:
* We need to release micro-sam on PyPI. Then napari-hub will automatically scrape PyPI and will find micro-sam, because we already have the `Framework :: napari` classifier.
* Because micro-sam requires some dependencies only available on conda (not pypi), we will...
    * Not worry about the fact it will not install everything correctly if users try `pip install micro-sam` (this is not great, but there is no good alternative if we want micro-sam discoverable on the napari-hub)
    * Add a line to the documentation (maybe [around here](https://github.com/computational-cell-analytics/micro-sam/blob/6a2a3fe87751650208000a443860fcf262186eed/doc/installation.md?plain=1#L8)) to tell users please do not use pip to install micro-sam. Hopefully anyone with installation problems will see this page and then try again with conda or from source.

**Comment by GenevieveBuckley** [comment]
FYI: it seems that the "Image Modality" labels can only be controlled by adding a `.napari-hub/config.yml` file. This is because this key is not (yet?) supported by the napari manifest `napari.yaml` file.

We could add that too, I guess, but it does feel messy having so many config files scattered around. 

I only found one plugin on the hub using the Image Modality labels (probably because it is not well-documented how to set them up). It was the [napari-biomag-annotator plugin, see the example `.napari-hub/config.yml` file here](https://github.com/biomag-lab/napari-biomag-annotator/blob/main/.napari/config.yml). 

Note: That `.napari-hub/config.yml` file does list a lot more labels than I see actually being used by [the napari-hub page](https://www.napari-hub.org/plugins/napari-biomag-annotator?imageModality=Confocal+microscopy), so I'm not sure if some of these are effectively not being used. It's possible only specific values are accepted, but I can't find good documentation about it, so this one example is the best we have to go on.

**Comment by constantinpape** [comment]
Thanks for looking into this @GenevieveBuckley. Let's go ahead and put a "dummy" micro_sam package on pip then so that it can be installed via napari.

Would you have time to look into this? (There's no hurry!)

**Comment by GenevieveBuckley** [comment]
> Thanks for looking into this @GenevieveBuckley. Let's go ahead and put a "dummy" micro_sam package on pip then so that it can be installed via napari.
> 
> Would you have time to look into this? (There's no hurry!)

I've made a PR here: https://github.com/computational-cell-analytics/micro-sam/pull/606

**Comment by GenevieveBuckley** [comment]
> I have made a new release now, but the `deploy` part of the action that would push the package to PyPI was skipped, see https://github.com/computational-cell-analytics/micro-sam/actions/runs/9222705341.
> 
> I can't see why in the log; any idea why this may happen @GenevieveBuckley?

There are two conditions for the `deploy` job:
1. The previous `update_release_draft` job in the `release_drafter` workflow completed successfully, **and**
2. If there is a tag `if: contains(github.ref, 'tags')`

I was assuming that the `deploy` job would see that the first job created a new tag, but perhaps this is not how things work. Maybe because that tag is being created from inside the `update_release_draft` job?

**Comment by GenevieveBuckley** [comment]
I guess the main question is: how does the current release drafter work?
Should the deploy job be turned into a step that runs after the others (possibly conditional on the results from a previous step?)
Is there ever a case where a release could be drafted, but we don't want anything uploaded to pypi?
