### ISSUE TITLE
skan module error when running napri from command line

### ISSUE THREAD

**Issue by JoannaLeng** [computational-cell-analytics/micro-sam#54]
I have created the sam environment and pip installed the sam module. I can run all the scripts named in the setup file eg "micro_sam.precompute_embeddings -h" but I get an error when I try to start the scripts with an image file or with napari. 

The command " napari -i .\test.jpg" gives me the error:

"12:34:57 ERROR napari.manifest -> 'skan' could not be imported: Could not find file 'napari.yaml' in module 'skan'"

**Comment by constantinpape** [comment]
Hi @JoannaLeng,
 
> I get an error when I try to start the scripts with an image file or with napari.

Does this error prevent the viewer from opening? Because it always happens when [skan](https://github.com/jni/skan) is installed in the environment but shouldn't actually affect the functionality.

See the video of running `examples/sam_annotator_2d.py` on my machine: it shows the `skan` error, but the plugin starts as expected.

https://github.com/computational-cell-analytics/micro-sam/assets/4263537/1c414fd7-e15f-4285-8619-1f196916aadf

**Comment by constantinpape** [comment]
@jni any idea on why napari throws the error `napari.manifest -> 'skan' could not be imported: Could not find file 'napari.yaml' in module 'skan'` when `skan` is installed?

**Comment by jni** [comment]
Oops! This is because of jni/skan#202. I'll cut a release right now. 😅

**Comment by jni** [comment]
This should be fixed by updating to skan 0.11.1, now available on PyPI. Should be in conda-forge also soon. 🙏

**Comment by constantinpape** [comment]
Awesome, thank you @jni!

**Comment by JoannaLeng** [comment]
Great! This has helped me move on with using this software.
