### ISSUE TITLE
Fix plugin / napari layout when expanding settings dialogs

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#542]
Currently expanding a settings dialog leads to some issues in the napari layout, for example loosing the slider to change the frame in view and loosing the button to maximize the window.

Below video shows an example where this happens for the 3d annotator. For @Marei33 this happens on start of the 3d annotator already.

https://github.com/computational-cell-analytics/micro-sam/assets/4263537/d9666d57-10bf-4bb5-868b-214ecc9daca9

Can we prevent this, e.g. by making the dock widget scrollable instead?

**Comment by lufre1** [comment]
Technically this could be solved by wrapping the annotator in a QScrollArea: 
```python
    if viewer is None:
        viewer = napari.Viewer()

    viewer.add_image(image, name="image")
    annotator = Annotator3d(viewer)

    # Trigger layer update of the annotator so that layers have the correct shape.
    # And initialize the 'committed_objects' with the segmentation result if it was given.
    annotator._update_image(segmentation_result=segmentation_result)

    scroll_area = QtWidgets.QScrollArea()
    scroll_area.setWidgetResizable(True)  # Allow widget to resize within scroll area
    scroll_area.setWidget(annotator)
    viewer.window.add_dock_widget(scroll_area)
```
This sadly does not work (has no effect at all). 

But i found a discussion about adding scrollbars to docks:
https://github.com/napari/napari/issues/4579
Which is not implemented yet.

I also tried to wrap widgets into a single scrollable widget in order to display the scrollable widget containing all necessary widgets for the annotator. This is not easy to implement due to the mixture of magic_factory (function_gui) and qtpy.widgets elements.

So the last approach was using a scrollable layout where the annotator is added and then it gets added to the dock. (like described in: https://stackoverflow.com/questions/28566161/how-to-make-qwidget-contents-scrollable-in-pyqt)
Sadly, this did not have any effect similar to the scrollable widget approach.

**Comment by constantinpape** [comment]
The scroll area works as expected, see #553. You have added it in a wrong location @lufre1. The code in `annoator_3d.py` (and the other annotator specific files) is only called when loading starting the annotation tool via python script or CLI, but not when starting it via the napari plugin interface. The correct way is to just make the annotator base class into a scroll area as in the PR.
