### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by haesleinhuepf** [computational-cell-analytics/micro-sam#615]
Hi all,

I just tried to install micro-sam as explained on [this page](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html):

```
mamba install -c conda-forge micro_sam
``` 

And I receive this error:
```
Looking for: ['micro_sam']

conda-forge/noarch                                  17.1MB @   5.3MB/s  4.0s
conda-forge/win-64                                  26.2MB @   4.7MB/s  6.8s

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides pytorch needed by micro_sam-0.0.2-pyhd8ed1ab_0
```

This command adding another conda channel worked:
```
mamba install -c conda-forge micro_sam -c pytorch
```

I suggest updating the documentation ;-)

Best,
Robert

**Comment by constantinpape** [comment]
Thanks @haesleinhuepf! I will take care of this in the next doc update.

**Comment by constantinpape** [comment]
This will be fixed by https://github.com/computational-cell-analytics/micro-sam/pull/617.

@haesleinhuepf I noticed that mamba tries to install a very old version:

> - nothing provides pytorch needed by micro_sam-0.0.2-pyhd8ed1ab_0

Maybe this error message is due to the dependency issue, but it's worth checking in your environment that an up-to-date version was installed after you have added the `pytorch` channel. The latest version is 1.0.0.

**Comment by constantinpape** [comment]
The installation documentation is now updated.

**Comment by haesleinhuepf** [comment]
Thanks!
