### ISSUE TITLE
Consistency in version numbering

### ISSUE THREAD

**Issue by GenevieveBuckley** [computational-cell-analytics/micro-sam#65]
I notice that although there is a 0.0.2 release, the version number in the `setup.py`file is still listed as 0.0.1 
This makes things a little confusing when checking whether you're using the latest version or not (this is how I noticed the discrepancy). 

https://github.com/computational-cell-analytics/micro-sam/blob/1958d01c8c99ca7eb855bebe537419bcd7bbbe42/setup.py#L8

Should the setup.py file be updated (or possibly even better, use a tool like [setuptools-scm](https://github.com/pypa/setuptools_scm/) to handle this automatically)?

**Comment by constantinpape** [comment]
Hi @GenevieveBuckley,
Thanks for pointing this out! I had a solution for this already, but just forgot to use the version loaded from `micro_sam/__version__.py`. It's fixed in #66.
(Note: this still requires to manually set the version in the `micro_sam/__version__.py` file upon publishing a release. Maybe it would be good to automate this more using `setuptools-scm`, I will read into it before the next release.)
