### ISSUE TITLE
Provide installation script for micro-sam

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#68]
So that users can install it without having to install conda themselves.

The best option I am aware of for this is conda-constructor: https://github.com/conda/constructor

An example for where it is used is here: https://github.com/hci-unihd/covid-if-annotations/tree/master/dev/deployment (might be a bit outdated though).

**Comment by paulhfu** [comment]
If I understood correctly, this can only install web-hosted packages into a newly generated conda env.
Will micro-sam become part a public package channel?
Otherwise we could also use Pyinstaller to create ready-to-run executables which then can be released.

**Comment by constantinpape** [comment]
> If I understood correctly, this can only install web-hosted packages into a newly generated conda env.

Yes, that's right.

> Will micro-sam become part a public package channel?

That's my plan and I want to work on it next week. See #76. I will look into this next week (probably will have time on Wednesday).

 > Otherwise we could also use Pyinstaller to create ready-to-run executables which then can be released.
 
 That's good to know! We should keep this in mind as a back-up if there are issues with putting `micro_sam` on conda-forge.

**Comment by constantinpape** [comment]
Hi @paulhfu ,
the conda-forge package should be there soon (I figured out how to circumvent the issues I ran into, and now only waiting on the PR to be reviewed and merged). So we can go ahead with the `conda/consturctor` solution.

Two comments on this:
- You will need to add `napari` as a dependency, because the `micro_sam` package doesn't have it as dependency (I had to do this to fix build issues and it's also a better solution because it enables installing `micro_sam` only as a library).
- Please make sure to list the `pytorch` conda channel with a higher priority as `conda-forge`, so that PyTorch is installed form official sources (this is better in general, and also the windows build won't work otherwise).

**Comment by paulhfu** [comment]
Hi @constantinpape,

Ok, I will do that. 
I experimented a bit. Here are my findings:
- I could not find a way to build a condition for the torch-with-cuda installation into the installer. We have to make two separate installers for that.
- I am assuming we need installers for Linux, MacOs and Win? I can make the ones for Win and Linux.
- The installer has some issues with the pip dependency of segment-anything but I think I can work around this by specifying a conda env.yaml file instead of writing the dependency list directly in the constructor file. Then it will generate a temporary env first, using conda and build the installer from that.
- It is also possible to use mamba as solver.

This tool is well documented. I think after the release we will be able to generate installer quickly.
I will open a PR with my experimental state.

**Comment by constantinpape** [comment]
> * I could not find a way to build a condition for the torch-with-cuda installation into the installer. We have to make two separate installers for that.

Ok, let's focus on the CPU builds for now, we can think about what to do for CUDA later.

> * I am assuming we need installers for Linux, MacOs and Win? I can make the ones for Win and Linux.

Yes, ideally we would provide installers for all three. If possible we would let the CI build the installers for all three automatically. (But for now let's not worry about that.)

> * The installer has some issues with the pip dependency of segment-anything but I think I can work around this by specifying a conda env.yaml file instead of writing the dependency list directly in the constructor file.

There is a conda package for segment anything: https://anaconda.org/conda-forge/segment-anything.
(And the `micro_sam` conda package will also depend on this, so you won't even need to list it explicitly).

> * It is also possible to use mamba as solver.

That's very good!

> I think after the release we will be able to generate installer quickly.
> I will open a PR with my experimental state.

Sounds good!
