### ISSUE TITLE
Segmentations are incorrect if a layer has non 1 `.scale`

### ISSUE THREAD

**Issue by psobolewskiPhD** [computational-cell-analytics/micro-sam#801]
I'm working with a user that has datafiles that have metadata imported via aicsimageio, so they layers inherit pixel scaling ~ (.5, .1, .1). Computing embeddings works fine, but then when using a point prompt and `Segment slice` the mask is totally wrong--too big.
If I change the layer scale to [1, 1, 1] then things work as expected, even without re-computing embeddings.
I see the same behavior with 2D images.

**Comment by constantinpape** [comment]
Thanks for reporting @psobolewskiPhD ! The problem must be that the coordinates read out of the shape or point layer don't match the image dimensions any more. We probably just need to reverse the scaling by dividing by the scale factor.

Do you want to give this a try yourself? Otherwise I can look into this next week.

**Comment by psobolewskiPhD** [comment]
I'll take a look and see how far I can get today.

**Comment by psobolewskiPhD** [comment]
OK! I got something working and it works when the z-coord of a point isn't precisely on a plane (ie. set using an orthogonal or oblique plane).

**Comment by constantinpape** [comment]
That's great! Feel free to open a draft PR if you want feedback. I will be able to take a look at it on Monday.

**Comment by constantinpape** [comment]
This is fixed now and is part of the new release. Thanks for the contribution @psobolewskiPhD !
