### ISSUE TITLE
use of the 'Images Series Annotator' in the Napari plugin

### ISSUE THREAD

**Issue by jazberna1** [computational-cell-analytics/micro-sam#808]
Hello,

This is not really an issue. I'm wondering if you could please tell me about the use of the 'Images Series Annotator' in the Napari plugin. I thought it could be used to segment batches of Z-stacks but when I tried to do so it got the following error (as in the attached screenshot) so I suspect it has a different purpose:
`Invalid image of shape (70, 570, 496, 3). Expect either 2D grayscale or 3D RGB image.`
 

<img width="651" alt="error image slice annotator" src="https://github.com/user-attachments/assets/c3c45a35-f936-48dd-bfac-b2dcf0c8bc13">

Thanks!
Jorge

**Comment by constantinpape** [comment]
Hi @jazberna1 ,

> . I'm wondering if you could please tell me about the use of the 'Images Series Annotator' in the Napari plugin. I thought it could be used to segment batches of Z-stacks

The image series annotator can be used to segment multiple images (2d data) or volumes (3d) data, in a high throughput fashion, by precomputing all embeddings and then opening the images / volumes immediately one after another.
See [documentation](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#image-series-annotator) and [video](https://youtu.be/HqRoImdTX3c) for details.

> Invalid image of shape (70, 570, 496, 3). Expect either 2D grayscale or 3D RGB image

The plugin expects that the volumes are saved as individual files, so instead of having a single file of shape `(70, 570, 496, 3)`, you would need to save it as 70 individual files (e.g. as tifs). This makes the design more flexible, by also supporting images / volumes of different shape.

I hope this helps!

**Comment by jazberna1** [comment]
Hi @constantinpape 

Thanks for the clarification. I see that the embeddings are calculated for multiple images. I was wondering, for the segmenation, is there a way to not have to click in 'Next Image [N]' buttom and segment all images in one go?

Thanks!
Jorge

**Comment by constantinpape** [comment]
The purpose of the plugin isn't just automatic segmentation, but interactive and automatic segmentation.

If you want to automatically segment many images you don't need to use the napari plugin, but can instead use our command line script `micro_sam.automatic_segmentation`. Run
```bash
micro_sam.automatic_segmentation -h
```
to get the explanation for how to use it.

**Comment by jazberna1** [comment]
Hi @constantinpape ,

Totally understood. I already had a go with `micro_sam.automatic_segmentation`, just wasn't sure about how the Napari plugin worked.

I am closing this ticket

Thanks!
Jorge
