### ISSUE TITLE
Resolving conda dependency and pytorch issues

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#813]
Given the recent deprecation of the pytorch conda channel, and the dependency issues, we should update the dependencies and builds for micro_sam. I think the best strategy would be to:
- Update our environment files and build instructions so that we only depend on conda-forge.
    - Create specific environment files / instructions for windows that depend on the pytorch channel (*)
- Clean up the micro_sam feedstock on conda forge to remove strict nifty pins and any other hacks, so that it can be used without issues for Linux / OSX.
- Update windows installation instructions with hard pins for compatible packages, see https://github.com/conda-forge/micro_sam-feedstock/pull/25#issuecomment-2556881057  (*)
- Remove the windows specific solutions (*) once pytorch on conda-forge supports windows, see https://github.com/conda-forge/pytorch-cpu-feedstock/pull/231  

@hmaarrfk : from what we discussed in the other issues / PRs I think that this would be the cleanest solution. Let me know what you think, then I will start implementing this today in the evening (European time)

**Comment by hmaarrfk** [comment]
Hey Thank you so much for your willingness to work through this and to help make conda-forge a "better place" to work with upstream developers!!!

> Update windows installation instructions with hard pins for compatible packages, see 

do note that this makes it generally difficult for users to add any additional packages after that "1" command. This makes the environment very fragile.

I know all too well the feeling of being pulled in different directions by users / developers so I didn't want to force that upon you.

> Remove the windows specific solutions (*) once pytorch on conda-forge supports windows

Is napari packaged on Anaconda's default channel? It seems like no, otherwise, I would say that pushing windows users to Anaconda's channel is "acceptable" (even though they would have to pay. I think Anaconda is 100% in their right asking for people to subscribe.

I'm crossing my fingers for a christmas miracle. I've held off on publishign a CPU-only windows package for years since I thought it was unacceptably slow! I'm glad there is now momentum by others that have picked up the GPU work!

**Comment by hmaarrfk** [comment]
In short, I am in all in favor of simplifying the recipe. but I'm not blind to the support challenges you face!

**Comment by constantinpape** [comment]
> do note that this makes it generally difficult for users to add any additional packages after that "1" command. This makes the environment very fragile.
> 
> I know all too well the feeling of being pulled in different directions by users / developers so I didn't want to force that upon you.

I don't think that it makes things worse compared to the current state though, since it just moves the pin from the recipe to the installation command for windows. In any case, our windows users usually won't install anything else in the environments since they are usually not developers (which are mostly on a unix system).

I have started with the changes to our environments in #814  (I'd like to do this before updating the recipe, because it's easier to debug). I will follow up with a few more concrete questions there.

**Comment by hmaarrfk** [comment]
> I'd like to do this before updating the recipe, because it's easier to debug

Honestly, I like to recommend that people that are in a "rush" to get something in, typically upload the "rushed packages" to their own channels.

I took my own medicine ;)

**Comment by constantinpape** [comment]
This is now all taken care of, and I made a new release for it as well. I will close it and create a dedicated issue for tracking the windows related things.
